name: GitHub Actions Build and Deploy playground
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
          version: latest
        
    - name: Build website
      run: pnpm playground:build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/playground/dist # The folder the action should deploy.
          commit-message: website deploy
